---
routes:
    helloWorld:
        path: /
        controller: Yuzi\Controller\ExampleController
        action:
            -
                path: /
                listener: indexAction
                method: [ GET, POST ]